### ISSUE TITLE
issue with ssw-py

### ISSUE THREAD

**Issue by MarineBergot** [stjude/indelPost#2]
Hi!
i'm trying to install indelpost in order to test it for our production pipeline unfortunatly i have some issues with installation.
I'm currently working on a server with CentOS Linux release 7.7.1908, Python 3.6.13
I installed indelpost with pip:
/work/gad/shared/bin/miniconda3/bin/pip install indelpost
WARNING: Ignoring invalid distribution -yparsing (/beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages)
WARNING: Ignoring invalid distribution -yparsing (/beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages)
Requirement already satisfied: indelpost in /beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/indelpost-0.1.7-py3.6-linux-x86_64.egg (0.1.7)
Requirement already satisfied: ssw-py in /beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/ssw_py-0.2.6-py3.6-linux-x86_64.egg (from indelpost) (0.2.6)
Requirement already satisfied: numpy>=1.16.0 in /beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages (from indelpost) (1.19.5)
Requirement already satisfied: pysam>=0.15.0 in /beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages (from indelpost) (0.16.0.1)
Requirement already satisfied: cython>=0.29.12 in /beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages (from indelpost) (0.29.24)
WARNING: Ignoring invalid distribution -yparsing (/beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages)
WARNING: Ignoring invalid distribution -yparsing (/beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages)
WARNING: Ignoring invalid distribution -yparsing (/beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages)

pip 21.3.1

when i'm running python and tried to import indelpost lib i get this error : 
from ssw_lib import CSsw
>>> import indelpost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/indelpost-0.1.7-py3.6-linux-x86_64.egg/indelpost/__init__.py", line 1, in <module>
    from indelpost.variant import *
  File "indelpost/variant.pyx", line 4, in init indelpost.variant
  File "indelpost/localn.pyx", line 5, in init indelpost.localn
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/ssw/__init__.py", line 1, in <module>
    from . ssw_wrap import Aligner
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/ssw/ssw_wrap.py", line 259, in <module>
    class PyAlignRes(object):
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/ssw/ssw_wrap.py", line 274, in PyAlignRes
    cigar_int_to_len = libssw.cigar_int_to_len
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /work/gad/shared/bin/Complete-Striped-Smith-Waterman-Library/src/libssw.so: undefined symbol: cigar_int_to_len

i tried to find help on the github of ssw-py, i changed my PATH, with 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/work/gad/shared/bin/Complete-Striped-Smith-Waterman-Library/src

i tried to install ssw-py with pip but it's a complete fail that's why i tried by compiling source
if you have any idea to help i would be very gratefull!

thanks !

**Comment by rawagiha** [comment]
Thanks for your interest in the tool.

Would you please try:
1. uninstall ssw-py. Please delete related files as well.
2. uninstall indelpost
3. git clone https://github.com/Wyss/ssw-py.git
4. python setup.py install
5. pip install indelpost --no-binary indelpost --no-build-isolation

Please let me know what you get.

**Comment by MarineBergot** [comment]
thanks for your quick answer! i followed your instructions, now i have other error ^^'

Successfully built indelpost
WARNING: Ignoring invalid distribution -yparsing (/beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages)
Installing collected packages: indelpost
WARNING: Ignoring invalid distribution -yparsing (/beegfs/data/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages)
Successfully installed indelpost-0.1.7



python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import indelpost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/indelpost/__init__.py", line 1, in <module>
    from indelpost.variant import *
  File "indelpost/variant.pyx", line 4, in init indelpost.variant
  File "indelpost/localn.pyx", line 5, in init indelpost.localn
  File "/beegfs/data/work/gad/shared/bin/ssw-py/ssw/__init__.py", line 1, in <module>
    from .sswpy import *
ModuleNotFoundError: No module named 'ssw.sswpy'
>>>

**Comment by rawagiha** [comment]
Let's test ssw-py alone to confirm that something is wrong with ssw-py installation. 
Please run the following minimal example:

from ssw import SSW
a = SSW()
a.setReference("AATTGG")
a.setRead("AATGG")
b = a.align()
print(b)

Expected result:
`Alignment(CIGAR='2M1D3M', optimal_score=7, sub_optimal_score=0, reference_start=0, reference_end=5, read_start=0, read_end=4)`

I am guessing you would have the same import error. On the meantime, I will try to reproduce your issue on my side.
It may take time. Your patience much appreciated.

**Comment by MarineBergot** [comment]
ma5840be@krenek02:python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ssw import SSW
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/ssw/__init__.py", line 1, in <module>
    from . ssw_wrap import Aligner
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/ssw/ssw_wrap.py", line 54, in <module>
    class Aligner(object):
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/ssw/ssw_wrap.py", line 65, in Aligner
    libssw = load_ssw_library()
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/ssw/ssw_wrap.py", line 31, in load_ssw_library
    return cdll.LoadLibrary(libname)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libssw.so: cannot open shared object file: No such file or directory


no problem, thanks a lot for your help !

**Comment by rawagiha** [comment]
Ok. So..., something wrong with the ssw-py build. I will get back to you when I come up with solutions. I am so sorry for this inconvenience.

**Comment by rawagiha** [comment]
Hi. 
I am still working on this issue. 
When I checked my directory where ssw-py is installed,  `sswpy.cpython-37m-x86_64-linux-gnu.so` is the only .so file. I cannot find the files such as `libssw.so` in the error message. 

> i tried to install ssw-py with pip but it's a complete fail that's why i tried by compiling source

1.  Uninstall ssw-py.  You may need to manually remove some files. 
2.  Visit https://pypi.org/project/ssw-py/#files 
3.  Manually download `ssw-py-0.2.6.tar.gz`
4.  `pip install ssw-py-0.2.6.tar.gz`

Does this work for you?

**Comment by MarineBergot** [comment]
things seems to improve! i tried what you asked, ssw seems to work but i still have issue:

Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ssw import SSW
>>> a = SSW()
>>> a.setReference("AATTGG")
>>> a.setRead("AATGG")
>>> b = a.align()
>>> print(b)
Alignment(CIGAR='2M1D3M', optimal_score=7, sub_optimal_score=0, reference_start=0, reference_end=5, read_start=0, read_end=4)


>>> import pysam                                           
>>> from indelpost import Variant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/gad/shared/bin/miniconda3/lib/python3.6/site-packages/indelpost/__init__.py", line 2, in <module>
    from indelpost.varaln import *
  File "indelpost/varaln.pyx", line 1, in init indelpost.varaln
AttributeError: module 'pysam.libcalignmentfile' has no attribute 'IteratorColumnAll'
>>> 
 is it normal ? maybe i forgot a part?

thanks again for your precious help!

**Comment by rawagiha** [comment]
Glad to know it worked! 

To solve the new problem, would you please try:

1. uninstall pysam and cython
2. `pip install cython`
3.  `pip install pysam`
4.  `pip install indelpost --no-binary indelpost --no-build-isolation`

**Comment by MarineBergot** [comment]
wooow finally!!! thanks so much for your help :) i succeed! 


Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ssw import SSW
>>> import indelpost
>>>

**Comment by rawagiha** [comment]
I also appreciate your patience. Please let me know for any questions/issues.
