### ISSUE TITLE
Indel Length Limit and SNV/MNV Allele Counting

### ISSUE THREAD

**Issue by tinyheero** [stjude/indelPost#6]
Hi there,

I have two questions about the allele counting capabilities of indelPost that I was hoping I could get some clarity on:

1. Is there a specific indel length that indelPost struggles to accurately calculate allele counts for? For instance, would you expect indelPost to perform well at say an indel length of 51 for reads that are 150 base pairs long?
2. While indelPost is designed for indel, is it possible to use its allele counting capabilities for SNVs and MNVs? 

Kind regards,

Fong

**Comment by rawagiha** [comment]
@tinyheero 

1. There is no hard threshold for indel length. For 150-bp read, we have tested up to length of 72 (deletion). Insertions can be tougher as they contain more non-reference sequences and, thus, are less tolerated in the realignment step. In our experience, insertions <50 bp are usually fine in 150-bp reads.

2. Actually, indelPost does the allele counting job for SNVs, although it is not an official feature. The usage is same as indel case. For MNVs, it is not supported. Please let me know if this is critically needed for your application. I may have some time to implement.

**Comment by tinyheero** [comment]
Thanks @rawagiha:

1. Makes sense that insertions would be more difficult. Good to know that you have tested up to 72 bp deletion. Did you stop simply stop at 72 or was it that performance was deflated above 72? Presumably, the performance should not be affected by deletion length? The flanking sequences should match to the reference. Asking because I am wondering if it makes sense to set a threshold on the indel length to use indelPost
2. MNV support would be amazing! It would be great to have a single tool that could do allele counting for all variant types. Especially the fact that MNVs could benefit from the local alignment step.

**Comment by rawagiha** [comment]
@tinyheero 
The 72-bp length is simply because that happened to be the longest indel in our test dataset. Generally, this tool is designed to process small indels, which are often defined < 50 bp. So, I would set the threshold to 50 if necessary. 

About MNV, I will try to make this happen.
I will close this issue for now and will get back to you once the MNV counting feature is ready to share (but, please do not expect too much...).

Thanks again for your interest.

**Comment by tinyheero** [comment]
Thanks @rawagiha !

**Comment by rawagiha** [comment]
@tinyheero:

I just remembered that the MNV counting function is already included. In addition to typical cases like TGGG>CACA, it also works for short-segment substitutions: TCTTT>CCTTC (the middle "CTT" is preserved). I am sorry. I totally forgot about this.

**Comment by tinyheero** [comment]
Amazing! Looking forward to trying it out. Thanks.
